version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Container1/Dockerfile
#    tty: true
#    stdin_open: true
    networks:
      docker_net:
        ipv4_address: 172.0.0.2 
    ports:
      - "20022:22"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  client:
    build:
      context: .
      dockerfile: Container2/Dockerfile
#    tty: true
#    stdin_open: true
    networks:
      docker_net:
        ipv4_address: 172.0.0.3
    ports:
      - "10022:22"

networks:
  docker_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.0.0.0/24
          gateway: 172.0.0.1
