version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Container1/Dockerfile
    container_name: memcached_server
    ports:
      - "20022:22"
  client:
    build:
      context: .
      dockerfile: Container2/Dockerfile
    ports:
      - "10022:22"
